[package]
name = "gaiarusted"
version = "1.1.8"
edition = "2021"
description = "A Rust compiler written in Rust: from source to x86-64 Linux executables, with no dependencies"
license = "MIT"
repository = "https://github.com/Mazigaming/GaiaRusted"
readme = "README.md"
keywords = ["compiler", "rust", "x86-64", "codegen", "optimizer"]
categories = ["development-tools::compiler"]

[lib]
name = "gaiarusted"
path = "src/lib.rs"

[[bin]]
name = "gaiarusted"
path = "src/bin/gaiarusted.rs"

[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[dependencies]

[dev-dependencies]

