//! # Async Function Lowering Integration
//!
//! This module integrates the state_machine.rs module into the actual
//! compiler pipeline, transforming async functions into state machines.

use crate::async_await::state_machine::{
    generate_poll_method, generate_state_struct, AwaitPoint, StateId, StateMachine,
};
use crate::lowering::{HirExpression, HirItem, HirStatement, HirType};
use std::collections::HashMap;

/// Transform async functions into state machines
///
/// This function iterates through all HIR items and converts any async functions
/// into state machine implementations.
pub fn transform_async_functions(hir_items: Vec<HirItem>) -> Vec<HirItem> {
    let mut result = Vec::new();

    for item in hir_items {
        match item {
            HirItem::Function {
                name,
                generics,
                params,
                return_type,
                body,
                is_public,
                where_clause,
            } => {
                // Check if the function name suggests it's async (generated by async transformation)
                // or if it contains await expressions in its body
                let has_await = contains_await(&body);

                if has_await || name.contains("_async") || name.starts_with("__async_") {
                    // This is an async function - transform it to a state machine
                    let state_machine =
                        create_state_machine(&name, params.clone(), return_type.clone(), body);

                    // Generate the state struct
                    if let Ok(state_struct) = generate_state_struct(&state_machine) {
                        result.push(state_struct);
                    }

                    // Generate the poll method (as a new function)
                    if let Ok(HirItem::Function {
                        name,
                        params,
                        return_type,
                        body,
                        ..
                    }) = generate_poll_method(&state_machine)
                    {
                        // Create the poll method with the correct name
                        result.push(HirItem::Function {
                            name: format!("{}::poll", state_machine.func_name),
                            generics: vec![],
                            params,
                            return_type,
                            body,
                            is_public: false,
                            where_clause: vec![],
                        });
                    }

                    // Add a wrapper function that returns the Future
                    result.push(HirItem::Function {
                        name: name.clone(),
                        generics,
                        params,
                        return_type: Some(HirType::Named(format!(
                            "impl Future<Output = {}>",
                            return_type.clone().unwrap_or(HirType::Unknown)
                        ))),
                        body: vec![], // Empty body - will be handled at codegen
                        is_public,
                        where_clause,
                    });
                } else {
                    // Regular function - keep as is
                    result.push(HirItem::Function {
                        name,
                        generics,
                        params,
                        return_type,
                        body,
                        is_public,
                        where_clause,
                    });
                }
            }
            _ => {
                // Non-function items are kept as-is
                result.push(item);
            }
        }
    }

    result
}

/// Check if a body contains await expressions
fn contains_await(body: &[HirStatement]) -> bool {
    for stmt in body {
        if contains_await_stmt(stmt) {
            return true;
        }
    }
    false
}

fn contains_await_stmt(stmt: &HirStatement) -> bool {
    match stmt {
        HirStatement::Expression(expr) => contains_await_expr(expr),
        HirStatement::Let { init, .. } => contains_await_expr(init),
        HirStatement::Return(Some(expr)) => contains_await_expr(expr),
        HirStatement::If {
            then_body,
            else_body,
            ..
        } => {
            let in_then = then_body.iter().any(contains_await_stmt);
            let in_else = else_body
                .as_ref()
                .map(|b| b.iter().any(contains_await_stmt))
                .unwrap_or(false);
            in_then || in_else
        }
        HirStatement::While { body, .. } => body.iter().any(contains_await_stmt),
        HirStatement::For { body, .. } => body.iter().any(contains_await_stmt),
        _ => false,
    }
}

fn contains_await_expr(expr: &HirExpression) -> bool {
    match expr {
        HirExpression::Await { .. } => true,
        HirExpression::Call { args, .. } => args.iter().any(contains_await_expr),
        HirExpression::MethodCall { args, .. } => args.iter().any(contains_await_expr),
        HirExpression::BinaryOp { left, right, .. } => {
            contains_await_expr(left) || contains_await_expr(right)
        }
        HirExpression::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            let in_cond = contains_await_expr(condition);
            let in_then = then_body.iter().any(contains_await_stmt);
            let in_else = else_body
                .as_ref()
                .map(|b| b.iter().any(contains_await_stmt))
                .unwrap_or(false);
            in_cond || in_then || in_else
        }
        HirExpression::While { body, .. } => body.iter().any(contains_await_stmt),
        HirExpression::Match { arms, .. } => arms
            .iter()
            .any(|arm| arm.body.iter().any(contains_await_stmt)),
        HirExpression::Block(stmts, final_expr) => {
            let in_stmts = stmts.iter().any(contains_await_stmt);
            let in_expr = final_expr
                .as_ref()
                .map(|e| contains_await_expr(e))
                .unwrap_or(false);
            in_stmts || in_expr
        }
        _ => false,
    }
}

/// Create a state machine from an async function
fn create_state_machine(
    func_name: &str,
    params: Vec<(String, HirType)>,
    return_type: Option<HirType>,
    body: Vec<HirStatement>,
) -> StateMachine {
    // Extract await points from the function body
    let mut await_points = Vec::new();
    let mut local_vars = HashMap::new();
    let mut state_id = 0;

    extract_awaits_from_body(&body, &mut await_points, &mut local_vars, &mut state_id);

    StateMachine::new(
        func_name.to_string(),
        params,
        return_type.unwrap_or(HirType::Named("()".to_string())),
        await_points,
        local_vars,
    )
}

/// Recursively extract await points from the function body
fn extract_awaits_from_body(
    body: &[HirStatement],
    await_points: &mut Vec<AwaitPoint>,
    local_vars: &mut HashMap<String, HirType>,
    state_id: &mut usize,
) {
    for stmt in body {
        extract_awaits_from_stmt(stmt, await_points, local_vars, state_id);
    }
}

fn extract_awaits_from_stmt(
    stmt: &HirStatement,
    await_points: &mut Vec<AwaitPoint>,
    local_vars: &mut HashMap<String, HirType>,
    state_id: &mut usize,
) {
    match stmt {
        HirStatement::Let { name, ty, init, .. } => {
            local_vars.insert(name.clone(), ty.clone());
            extract_awaits_from_expr(init, await_points, local_vars, state_id);
        }
        HirStatement::Expression(expr) => {
            extract_awaits_from_expr(expr, await_points, local_vars, state_id);
        }
        HirStatement::Return(Some(expr)) => {
            extract_awaits_from_expr(expr, await_points, local_vars, state_id);
        }
        HirStatement::If {
            then_body,
            else_body,
            ..
        } => {
            for s in then_body {
                extract_awaits_from_stmt(s, await_points, local_vars, state_id);
            }
            if let Some(else_b) = else_body {
                for s in else_b {
                    extract_awaits_from_stmt(s, await_points, local_vars, state_id);
                }
            }
        }
        HirStatement::While { body, .. } => {
            for s in body {
                extract_awaits_from_stmt(s, await_points, local_vars, state_id);
            }
        }
        HirStatement::For { body, .. } => {
            for s in body {
                extract_awaits_from_stmt(s, await_points, local_vars, state_id);
            }
        }
        _ => {}
    }
}

fn extract_awaits_from_expr(
    expr: &HirExpression,
    await_points: &mut Vec<AwaitPoint>,
    local_vars: &mut HashMap<String, HirType>,
    state_id: &mut usize,
) {
    match expr {
        HirExpression::Await { value } => {
            let state_before = StateId(*state_id);
            *state_id += 1;
            let state_after = StateId(*state_id);

            await_points.push(AwaitPoint {
                id: await_points.len(),
                state_before,
                state_after,
                expr: *(*value).clone(),
                result_var: None,
                output_type: HirType::Unknown,
            });
        }
        HirExpression::Call { args, .. } => {
            for arg in args {
                extract_awaits_from_expr(arg, await_points, local_vars, state_id);
            }
        }
        HirExpression::MethodCall { args, .. } => {
            for arg in args {
                extract_awaits_from_expr(arg, await_points, local_vars, state_id);
            }
        }
        HirExpression::BinaryOp { left, right, .. } => {
            extract_awaits_from_expr(left, await_points, local_vars, state_id);
            extract_awaits_from_expr(right, await_points, local_vars, state_id);
        }
        HirExpression::If {
            then_body,
            else_body,
            ..
        } => {
            for s in then_body {
                extract_awaits_from_stmt(s, await_points, local_vars, state_id);
            }
            if let Some(else_b) = else_body {
                for s in else_b {
                    extract_awaits_from_stmt(s, await_points, local_vars, state_id);
                }
            }
        }
        HirExpression::While { body, .. } => {
            for s in body {
                extract_awaits_from_stmt(s, await_points, local_vars, state_id);
            }
        }
        HirExpression::Match { arms, .. } => {
            for arm in arms {
                for s in &arm.body {
                    extract_awaits_from_stmt(s, await_points, local_vars, state_id);
                }
            }
        }
        HirExpression::Block(stmts, final_expr) => {
            for s in stmts {
                extract_awaits_from_stmt(s, await_points, local_vars, state_id);
            }
            if let Some(e) = final_expr {
                extract_awaits_from_expr(e, await_points, local_vars, state_id);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::async_await::{AwaitPoint, StateId, StateMachine};
    use crate::lowering::{HirExpression, HirItem, HirStatement, HirType, LowerResult};
    use crate::parser::ast::{Expression, Item, Statement};

    #[test]
    fn test_transform_async_functions_no_async() {
        // Test with no async functions
        let input_items = vec![HirItem::Function {
            name: "regular_func".to_string(),
            generics: vec![],
            params: vec![],
            return_type: Some(HirType::Int32),
            body: vec![HirStatement::Return(Some(HirExpression::Integer(42)))],
            is_public: false,
            where_clause: vec![],
        }];

        let result = transform_async_functions(input_items.clone());
        assert_eq!(result.len(), input_items.len());
    }

    #[test]
    fn test_transform_async_functions_with_async() {
        // Test with async function
        let input_items = vec![HirItem::Function {
            name: "async_func".to_string(),
            generics: vec![],
            params: vec![],
            return_type: Some(HirType::Int32),
            body: vec![HirStatement::Return(Some(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            }))],
            is_public: false,
            where_clause: vec![],
        }];

        let result = transform_async_functions(input_items);
        // Should transform the async function
        assert!(!result.is_empty());
    }

    #[test]
    fn test_contains_await() {
        let body = vec![HirStatement::Expression(HirExpression::Await {
            value: Box::new(HirExpression::Integer(42)),
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_let() {
        let body = vec![HirStatement::Let {
            name: "x".to_string(),
            mutable: false,
            ty: HirType::Int32,
            init: HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            },
        }];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_if() {
        let body = vec![HirStatement::Expression(HirExpression::If {
            condition: Box::new(HirExpression::Bool(true)),
            then_body: vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            })],
            else_body: None,
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_transform_async_functions_mixed() {
        // Test with mix of async and sync functions
        let input_items = vec![
            HirItem::Function {
                name: "sync_func".to_string(),
                generics: vec![],
                params: vec![],
                return_type: Some(HirType::Int32),
                body: vec![HirStatement::Return(Some(HirExpression::Integer(1)))],
                is_public: false,
                where_clause: vec![],
            },
            HirItem::Function {
                name: "async_func".to_string(),
                generics: vec![],
                params: vec![],
                return_type: Some(HirType::Int32),
                body: vec![
                    HirStatement::Expression(HirExpression::Await {
                        value: Box::new(HirExpression::Integer(42)),
                    }),
                    HirStatement::Return(Some(HirExpression::Integer(0))),
                ],
                is_public: false,
                where_clause: vec![],
            },
        ];

        let result = transform_async_functions(input_items);

        // Should have sync function unchanged plus async transformations
        let sync_count = result
            .iter()
            .filter(|item| matches!(item, HirItem::Function { name, .. } if name == "sync_func"))
            .count();
        assert_eq!(sync_count, 1, "Should preserve sync function");

        // Should have async transformations
        assert!(result.len() > 2, "Should have async transformations");
    }

    #[test]
    fn test_contains_await_in_expression() {
        let body = vec![HirStatement::Expression(HirExpression::Await {
            value: Box::new(HirExpression::Integer(42)),
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_let_initializer() {
        let body = vec![HirStatement::Let {
            name: "x".to_string(),
            ty: HirType::Int32,
            init: HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            },
            mutable: false,
        }];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_return() {
        let body = vec![HirStatement::Return(Some(HirExpression::Await {
            value: Box::new(HirExpression::Integer(42)),
        }))];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_if_condition() {
        let body = vec![HirStatement::Expression(HirExpression::If {
            condition: Box::new(HirExpression::Await {
                value: Box::new(HirExpression::Integer(1)),
            }),
            then_body: vec![HirStatement::Return(Some(HirExpression::Integer(42)))],
            else_body: None,
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_if_branches() {
        let body = vec![HirStatement::Expression(HirExpression::If {
            condition: Box::new(HirExpression::Integer(1)),
            then_body: vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            })],
            else_body: Some(vec![HirStatement::Return(Some(HirExpression::Integer(0)))]),
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_binary_op() {
        let body = vec![HirStatement::Expression(HirExpression::BinaryOp {
            left: Box::new(HirExpression::Await {
                value: Box::new(HirExpression::Integer(1)),
            }),
            op: crate::lowering::BinaryOp::Add,
            right: Box::new(HirExpression::Integer(2)),
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_call_args() {
        let body = vec![HirStatement::Expression(HirExpression::Call {
            func: Box::new(HirExpression::Variable("func".to_string())),
            args: vec![HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            }],
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_in_match_arms() {
        let body = vec![HirStatement::Expression(HirExpression::Match {
            scrutinee: Box::new(HirExpression::Integer(1)),
            arms: vec![crate::lowering::MatchArm {
                pattern: "42".to_string(),
                guard: None,
                body: vec![HirStatement::Expression(HirExpression::Await {
                    value: Box::new(HirExpression::Integer(42)),
                })],
            }],
        })];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_no_await() {
        let body = vec![
            HirStatement::Let {
                name: "x".to_string(),
                ty: HirType::Int32,
                init: HirExpression::Integer(1),
                mutable: false,
            },
            HirStatement::Return(Some(HirExpression::Integer(42))),
        ];
        assert!(!contains_await(&body));
    }

    #[test]
    fn test_no_await_complex() {
        let body = vec![
            HirStatement::Let {
                name: "x".to_string(),
                ty: HirType::Int32,
                init: HirExpression::BinaryOp {
                    left: Box::new(HirExpression::Integer(1)),
                    op: crate::lowering::BinaryOp::Add,
                    right: Box::new(HirExpression::Integer(2)),
                },
                mutable: false,
            },
            HirStatement::Expression(HirExpression::Call {
                func: Box::new(HirExpression::Variable("println".to_string())),
                args: vec![HirExpression::Integer(42)],
            }),
            HirStatement::Return(Some(HirExpression::Variable("x".to_string()))),
        ];
        assert!(!contains_await(&body));
    }

    #[test]
    fn test_contains_await_while_loop() {
        let body = vec![HirStatement::While {
            condition: Box::new(HirExpression::Integer(1)),
            body: vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            })],
        }];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_contains_await_for_loop() {
        let body = vec![HirStatement::For {
            var: "_i".to_string(),
            iter: Box::new(HirExpression::Integer(1)),
            body: vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            })],
        }];
        assert!(contains_await(&body));
    }

    #[test]
    fn test_create_state_machine_basic() {
        let params = vec![
            ("x".to_string(), HirType::Int32),
            ("y".to_string(), HirType::Int64),
        ];
        let return_type = Some(HirType::Int32);
        let body = vec![
            HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            }),
            HirStatement::Return(Some(HirExpression::Integer(0))),
        ];

        let state_machine = create_state_machine("test_func", params, return_type, body);

        assert_eq!(state_machine.func_name, "test_func");
        assert_eq!(state_machine.params.len(), 2);
        assert_eq!(state_machine.return_type, HirType::Int32);
        assert!(state_machine.await_points.len() == 1); // Should find await point
    }

    #[test]
    fn test_create_state_machine_no_await() {
        let params = vec![];
        let return_type = Some(HirType::Int32);
        let body = vec![HirStatement::Return(Some(HirExpression::Integer(42)))];

        let state_machine = create_state_machine("sync_func", params, return_type, body);

        assert_eq!(state_machine.func_name, "sync_func");
        assert!(state_machine.await_points.is_empty()); // No await points
    }

    #[test]
    fn test_create_state_machine_multiple_awaits() {
        let params = vec![];
        let return_type = Some(HirType::Int32);
        let body = vec![
            HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(1)),
            }),
            HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(2)),
            }),
            HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(3)),
            }),
            HirStatement::Return(Some(HirExpression::Integer(0))),
        ];

        let state_machine = create_state_machine("multi_await_func", params, return_type, body);

        assert_eq!(state_machine.await_points.len(), 3);
        assert_eq!(state_machine.await_points[0].id, 0);
        assert_eq!(state_machine.await_points[1].id, 1);
        assert_eq!(state_machine.await_points[2].id, 2);
    }

    #[test]
    fn test_extract_awaits_from_body() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let body = vec![
            HirStatement::Let {
                name: "x".to_string(),
                ty: HirType::Int32,
                init: HirExpression::Integer(1),
                mutable: false,
            },
            HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            }),
            HirStatement::Let {
                name: "y".to_string(),
                ty: HirType::Int32,
                init: HirExpression::Integer(2),
                mutable: false,
            },
        ];

        extract_awaits_from_body(&body, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 1);
        assert_eq!(await_points[0].id, 0);
        assert_eq!(local_vars.len(), 2); // x and y
        assert!(local_vars.contains_key("x"));
        assert!(local_vars.contains_key("y"));
    }

    #[test]
    fn test_extract_awaits_nested_structures() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let body = vec![HirStatement::Expression(HirExpression::If {
            condition: Box::new(HirExpression::Integer(1)),
            then_body: vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            })],
            else_body: Some(vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(43)),
            })]),
        })];

        extract_awaits_from_body(&body, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 2);
        assert_eq!(await_points[0].id, 0);
        assert_eq!(await_points[1].id, 1);
    }

    #[test]
    fn test_extract_awaits_from_stmt_let() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let stmt = HirStatement::Let {
            name: "x".to_string(),
            ty: HirType::Int32,
            init: HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            },
            mutable: false,
        };

        extract_awaits_from_stmt(&stmt, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 1);
        assert_eq!(local_vars.len(), 1);
        assert_eq!(local_vars["x"], HirType::Int32);
    }

    #[test]
    fn test_extract_awaits_from_stmt_return() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let stmt = HirStatement::Return(Some(HirExpression::Await {
            value: Box::new(HirExpression::Integer(42)),
        }));

        extract_awaits_from_stmt(&stmt, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 1);
        assert_eq!(local_vars.len(), 0);
    }

    #[test]
    fn test_extract_awaits_from_stmt_control_flow() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let stmt = HirStatement::While {
            condition: Box::new(HirExpression::Integer(1)),
            body: vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            })],
        };

        extract_awaits_from_stmt(&stmt, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 1);
    }

    #[test]
    fn test_extract_awaits_from_expr_await() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let expr = HirExpression::Await {
            value: Box::new(HirExpression::Integer(42)),
        };

        extract_awaits_from_expr(&expr, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 1);
        assert_eq!(await_points[0].id, 0);
        assert!(await_points[0].result_var.is_none());
    }

    #[test]
    fn test_extract_awaits_from_expr_binary() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let expr = HirExpression::BinaryOp {
            left: Box::new(HirExpression::Await {
                value: Box::new(HirExpression::Integer(1)),
            }),
            op: crate::lowering::BinaryOp::Add,
            right: Box::new(HirExpression::Await {
                value: Box::new(HirExpression::Integer(2)),
            }),
        };

        extract_awaits_from_expr(&expr, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 2);
        assert_eq!(await_points[0].id, 0);
        assert_eq!(await_points[1].id, 1);
    }

    #[test]
    fn test_extract_awaits_from_expr_call() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let expr = HirExpression::Call {
            func: Box::new(HirExpression::Variable("func".to_string())),
            args: vec![
                HirExpression::Await {
                    value: Box::new(HirExpression::Integer(1)),
                },
                HirExpression::Integer(2),
                HirExpression::Await {
                    value: Box::new(HirExpression::Integer(3)),
                },
            ],
        };

        extract_awaits_from_expr(&expr, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 2);
        assert_eq!(await_points[0].id, 0);
        assert_eq!(await_points[1].id, 1);
    }

    #[test]
    fn test_extract_awaits_from_expr_if() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let expr = HirExpression::If {
            condition: Box::new(HirExpression::Integer(1)),
            then_body: vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(42)),
            })],
            else_body: Some(vec![HirStatement::Expression(HirExpression::Await {
                value: Box::new(HirExpression::Integer(43)),
            })]),
        };

        extract_awaits_from_expr(&expr, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 2);
    }

    #[test]
    fn test_extract_awaits_from_expr_match() {
        let mut await_points = vec![];
        let mut local_vars = std::collections::HashMap::new();
        let mut state_id = 0;

        let expr = HirExpression::Match {
            scrutinee: Box::new(HirExpression::Integer(1)),
            arms: vec![crate::lowering::MatchArm {
                pattern: "42".to_string(),
                guard: None,
                body: vec![HirStatement::Expression(HirExpression::Await {
                    value: Box::new(HirExpression::Integer(42)),
                })],
            }],
        };

        extract_awaits_from_expr(&expr, &mut await_points, &mut local_vars, &mut state_id);

        assert_eq!(await_points.len(), 1);
    }

    #[test]
    fn test_transform_async_functions_error_handling() {
        // Test with malformed async function
        let input_items = vec![HirItem::Function {
            name: "broken_async".to_string(),
            generics: vec![],
            params: vec![],
            return_type: Some(HirType::Int32),
            body: vec![
                // This would cause issues in a real implementation
                HirStatement::Expression(HirExpression::Await {
                    value: Box::new(HirExpression::Integer(42)),
                }),
            ],
            is_public: false,
            where_clause: vec![],
        }];

        // Should not panic
        let result = std::panic::catch_unwind(|| transform_async_functions(input_items));

        assert!(
            result.is_ok(),
            "transform_async_functions should handle errors gracefully"
        );
    }

    #[test]
    fn test_transform_async_functions_empty() {
        let input_items = vec![];
        let result = transform_async_functions(input_items);
        assert!(result.is_empty());
    }

    #[test]
    fn test_transform_async_functions_large() {
        // Test with many functions
        let mut input_items = vec![];

        for i in 0..10 {
            input_items.push(HirItem::Function {
                name: format!("func_{}", i),
                generics: vec![],
                params: vec![],
                return_type: Some(HirType::Int32),
                body: vec![HirStatement::Return(Some(HirExpression::Integer(i as i64)))],
                is_public: false,
                where_clause: vec![],
            });
        }

        // Add one async function
        input_items.push(HirItem::Function {
            name: "async_func".to_string(),
            generics: vec![],
            params: vec![],
            return_type: Some(HirType::Int32),
            body: vec![
                HirStatement::Expression(HirExpression::Await {
                    value: Box::new(HirExpression::Integer(42)),
                }),
                HirStatement::Return(Some(HirExpression::Integer(0))),
            ],
            is_public: false,
            where_clause: vec![],
        });

        let result = transform_async_functions(input_items);

        // Should have 10 sync functions + async transformations
        assert!(
            result.len() >= 11,
            "Should preserve sync functions and add async transformations"
        );
    }

    #[test]
    fn test_contains_await_nested() {
        let body = vec![
            HirStatement::Let {
                name: "x".to_string(),
                mutable: false,
                ty: HirType::Int32,
                init: HirExpression::Integer(42),
            },
            HirStatement::Expression(HirExpression::If {
                condition: Box::new(HirExpression::Bool(true)),
                then_body: vec![HirStatement::Expression(HirExpression::Await {
                    value: Box::new(HirExpression::Variable("future".to_string())),
                })],
                else_body: None,
            }),
        ];

        assert!(contains_await(&body));
    }
}
