#!/usr/bin/env python3
"""Generate library/unicode.rs from the Unicode tables of rustc's core.

The tables decide how `{:?}` escapes characters: those that are not
printable, and those that extend a grapheme, are written as `\\u{..}`.
Taking them from the core library of the rustc in use keeps the output
identical to rustc's.

    python3 tools/gen_unicode.py [path/to/rust/library/core]
"""

import re
import subprocess
import sys
from pathlib import Path


def core_source() -> Path:
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    sysroot = subprocess.run(["rustc", "--print", "sysroot"], capture_output=True, text=True, check=True).stdout.strip()
    return Path(sysroot) / "lib/rustlib/src/rust/library/core"


def printable_section(text: str) -> str:
    """The checking functions and their tables, as core writes them."""
    body = text.split("\n", 2)[2].lstrip("\n")  # drop the "generated by" note
    body = body.replace("pub(crate) fn is_printable", "pub fn is_printable")
    body = body.replace("#[rustfmt::skip]\n", "")
    # Tables are statics: one copy in the data section, not one per use.
    return re.sub(r"^const (\w+): ", r"static \1: ", body, flags=re.M)


def module(text: str, name: str) -> str:
    return re.search(rf"pub mod {name} \{{(.*?)\n\}}", text, re.S).group(1)


def numbers(text: str):
    return [int(value, 0) for value in re.findall(r"0x[0-9a-fA-F]+|0b[01]+|\d+", text)]


def static_body(module_text: str, name: str) -> str:
    return re.search(rf"static {name}: [^=]+= (.*?);(?:\n|$)", module_text, re.S).group(1)


def skip_search_property(text: str, name: str, function: str, doc: str) -> str:
    """A property stored as runs of characters outside and inside it."""
    body = module(text, name)
    runs = re.findall(r"ShortOffsetRunHeader::new\((\d+), (\d+)\)", body)
    headers = [int(start) << 21 | int(prefix) for start, prefix in runs]
    offsets = numbers(static_body(body, "OFFSETS"))
    floor = re.search(r"\(c as u32\) >= (0x[0-9a-f]+) &&", body)
    test = f"(c as u32) >= {floor.group(1)} && " if floor else ""
    table = name.upper()
    return f"""
/// {doc}
pub fn {function}(c: char) -> bool {{
    {test}skip_search(c as u32, &{table}_RUNS, &{table}_OFFSETS)
}}

static {table}_RUNS: [u32; {len(headers)}] = [
{wrap(f"{value:#x}" for value in headers)}
];

static {table}_OFFSETS: [u8; {len(offsets)}] = [
{wrap(str(value) for value in offsets)}
];
"""


def bitset_property(text: str, name: str, function: str, doc: str) -> str:
    """A property stored as 64-bit words of a bitset, deduplicated."""
    body = module(text, name)
    table = name.upper()
    chunk_size = int(re.search(r"BITSET_INDEX_CHUNKS: \[\[u8; (\d+)\]", body).group(1))
    assert chunk_size == BITSET_CHUNK, f"{name}: chunks of {chunk_size}"
    chunks_map = numbers(static_body(body, "BITSET_CHUNKS_MAP"))
    index_chunks = [numbers(chunk) for chunk in re.findall(r"\[([^\[\]]*)\]", static_body(body, "BITSET_INDEX_CHUNKS")[1:-1])]
    canonical = numbers(static_body(body, "BITSET_CANONICAL"))
    mapping = re.findall(r"\((\d+), (\d+)\)", static_body(body, "BITSET_MAPPING"))
    return f"""
/// {doc}
pub fn {function}(c: char) -> bool {{
    bitset_search(c as u32, &{table}_CHUNKS_MAP, &{table}_INDEX_CHUNKS, &{table}_CANONICAL, &{table}_MAPPING)
}}

static {table}_CHUNKS_MAP: [u8; {len(chunks_map)}] = [
{wrap(str(value) for value in chunks_map)}
];

static {table}_INDEX_CHUNKS: [[u8; {BITSET_CHUNK}]; {len(index_chunks)}] = [
{chr(10).join("    [" + ", ".join(map(str, chunk)) + "]," for chunk in index_chunks)}
];

static {table}_CANONICAL: [u64; {len(canonical)}] = [
{wrap(f"{value:#x}" for value in canonical)}
];

static {table}_MAPPING: [(u8, u8); {len(mapping)}] = [
{wrap(f"({a}, {b})" for a, b in mapping)}
];
"""


def white_space_section(text: str) -> str:
    body = module(text, "white_space")
    table = numbers(static_body(body, "WHITESPACE_MAP"))
    return WHITE_SPACE.replace("{MAP}", wrap(str(value) for value in table)).replace("{LEN}", str(len(table)))


def conversions_section(text: str) -> str:
    body = module(text, "conversions")
    tables = []
    for name, ty in [("LOWERCASE_TABLE", "&[(char, u32)]"), ("LOWERCASE_TABLE_MULTI", "&[[char; 3]]"),
                     ("UPPERCASE_TABLE", "&[(char, u32)]"), ("UPPERCASE_TABLE_MULTI", "&[[char; 3]]")]:
        table = static_body(body, name).replace("\n        ", "\n    ").replace("\n    ]", "\n]")
        tables.append(f"static {name}: {ty} = {table};")
    return CONVERSIONS + "\n" + "\n\n".join(tables) + "\n"


def wrap(values, width=96) -> str:
    lines, line = [], "   "
    for value in values:
        if len(line) + len(value) + 2 > width:
            lines.append(line)
            line = "   "
        line += f" {value},"
    lines.append(line)
    return "\n".join(lines)


HEADER = """//! Unicode tables: the character properties `char` asks about
//! (alphabetic, numeric, cased...), case conversion, and which characters
//! `{:?}` writes as they are and which it escapes.
//!
//! Generated by `tools/gen_unicode.py` from the tables of rustc's core
//! library (Unicode {version}); do not edit by hand.

"""

BITSET_CHUNK = 16

SEARCHES = """
/// Whether `needle` falls in one of the ranges a property is made of:
/// `runs` say where each run of `offsets` starts (the index of its first
/// offset in the top 11 bits, its first character in the low 21), and the
/// offsets are the lengths of alternating ranges outside and inside.
fn skip_search(needle: u32, runs: &[u32], offsets: &[u8]) -> bool {
    let prefix_sum = |header: u32| header & ((1 << 21) - 1);
    let start_index = |header: u32| (header >> 21) as usize;
    let last = match runs.binary_search_by_key(&(needle << 11), |header| header << 11) {
        Ok(index) => index + 1,
        Err(index) => index,
    };
    let mut offset_index = start_index(runs[last]);
    let length = match runs.get(last + 1) {
        Some(&next) => start_index(next) - offset_index,
        None => offsets.len() - offset_index,
    };
    let previous = if last > 0 { prefix_sum(runs[last - 1]) } else { 0 };
    let total = needle - previous;
    let mut sum = 0;
    for _ in 0..(length - 1) {
        sum += offsets[offset_index] as u32;
        if sum > total {
            break;
        }
        offset_index += 1;
    }
    offset_index % 2 == 1
}

/// Whether bit `needle` of a property's bitset is set. The bitset's 64-bit
/// words are stored once each: `canonical` holds the distinct ones, and
/// `mapping` derives the others from them by inverting, shifting or
/// rotating.
fn bitset_search(needle: u32, chunks_map: &[u8], index_chunks: &[[u8; 16]], canonical: &[u64], mapping: &[(u8, u8)]) -> bool {
    let bucket = (needle / 64) as usize;
    let (chunk_map_index, chunk_piece) = (bucket / 16, bucket % 16);
    let Some(&chunk) = chunks_map.get(chunk_map_index) else { return false };
    let index = index_chunks[chunk as usize][chunk_piece] as usize;
    let word = match canonical.get(index) {
        Some(&word) => word,
        None => {
            let (real, how) = mapping[index - canonical.len()];
            let mut word = canonical[real as usize];
            if how & (1 << 6) != 0 {
                word = !word;
            }
            let quantity = how & ((1 << 6) - 1);
            if how & (1 << 7) != 0 {
                word >>= quantity as u64;
            } else {
                word = word.rotate_left(quantity as u32);
            }
            word
        }
    };
    word & (1 << (needle % 64)) != 0
}
"""

WHITE_SPACE = """
/// Is the character white space?
pub fn white_space(c: char) -> bool {
    match c as u32 >> 8 {
        0 => WHITESPACE_MAP[c as usize & 0xff] & 1 != 0,
        22 => c as u32 == 0x1680,
        32 => WHITESPACE_MAP[c as usize & 0xff] & 2 != 0,
        48 => c as u32 == 0x3000,
        _ => false,
    }
}

static WHITESPACE_MAP: [u8; {LEN}] = [
{MAP}
];
"""

CONVERSIONS = """
/// A table entry whose value has this bit set indexes the table of
/// multi-character conversions instead of being a character.
const INDEX_MASK: u32 = 0x400000;

/// The lower case of a character: up to three characters, padded with `\\0`.
pub fn to_lower(c: char) -> [char; 3] {
    if c.is_ascii() {
        return [c.to_ascii_lowercase(), '\\0', '\\0'];
    }
    convert(c, LOWERCASE_TABLE, LOWERCASE_TABLE_MULTI)
}

/// The upper case of a character: up to three characters, padded with `\\0`.
pub fn to_upper(c: char) -> [char; 3] {
    if c.is_ascii() {
        return [c.to_ascii_uppercase(), '\\0', '\\0'];
    }
    convert(c, UPPERCASE_TABLE, UPPERCASE_TABLE_MULTI)
}

fn convert(c: char, table: &[(char, u32)], multi: &[[char; 3]]) -> [char; 3] {
    match table.binary_search_by(|&(key, _)| key.cmp(&c)) {
        Ok(index) => {
            let value = table[index].1;
            match std::char::from_u32(value) {
                Some(converted) => [converted, '\\0', '\\0'],
                None => multi[(value & (INDEX_MASK - 1)) as usize],
            }
        }
        Err(_) => [c, '\\0', '\\0'],
    }
}
"""


def main() -> None:
    core = core_source()
    printable = (core / "src/unicode/printable.rs").read_text()
    data = (core / "src/unicode/unicode_data.rs").read_text()
    version = ".".join(re.search(r"UNICODE_VERSION: \(u8, u8, u8\) = \((\d+), (\d+), (\d+)\)", data).groups())
    sections = [
        HEADER.replace("{version}", version),
        printable_section(printable),
        skip_search_property(data, "alphabetic", "alphabetic", "Is the character alphabetic (a letter, or a mark or number letters use)?"),
        skip_search_property(data, "case_ignorable", "case_ignorable", "Is the character ignored between letters when deciding case (an apostrophe, a combining mark)?"),
        skip_search_property(data, "cased", "cased", "Does the character have case: is it upper, lower or title case?"),
        skip_search_property(data, "cc", "control", "Is the character a control character (general category Cc)?"),
        skip_search_property(data, "grapheme_extend", "is_grapheme_extended",
                             "Does the character extend the grapheme before it, as a combining mark does? Such\n/// characters are escaped by `{:?}`, which would otherwise attach them to the quote\n/// or backslash before them."),
        skip_search_property(data, "n", "numeric", "Is the character numeric: a digit, a letter-like number (Ⅻ), or another number (½)?"),
        bitset_property(data, "lowercase", "lowercase", "Is the character lower case?"),
        bitset_property(data, "uppercase", "uppercase", "Is the character upper case?"),
        white_space_section(data),
        conversions_section(data),
        SEARCHES,
    ]
    target = Path(__file__).resolve().parent.parent / "library/unicode.rs"
    target.write_text("".join(sections))
    print(f"wrote {target} (Unicode {version})")


if __name__ == "__main__":
    main()
